To_Do_List/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('to_do.urls')),
]

to_do/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import *

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('registration/', UserCreateView.as_view(), name='registration'),
    path('to-do-list/', login_required(ToDoListView.as_view()), name='to-do-list'),
    path('to-do-list/delete/<int:pk_to_do_list>', to_do_list_delete, name='to-do-list-delete'),
    path('add-record/', login_required(RecordView.as_view()), name='add-record'),
    path('record/delete/<int:pk_record>', record_delete, name='record-delete'),
    path('record/update/<int:pk_record>', record_update, name='record_update'),
    path('logout/', user_logout, name='logout'),
]

to_do/models.py
from django.contrib.auth.models import User
from django.db import models


class ToDoListTitle(models.Model):
    title = models.CharField('Name of the to-do list', max_length=25)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User')

    class Meta:
        verbose_name = 'To do list title'
        verbose_name_plural = 'To do list headers'

    def __str__(self):
        return self.title


class Record(models.Model):
    record_title = models.CharField('Record title', max_length=45)
    status = models.BooleanField('Status', default=False)
    title = models.ForeignKey(ToDoListTitle, models.CASCADE, verbose_name='Title')

    class Meta:
        verbose_name = 'Record'
        verbose_name_plural = 'Records'

    def __str__(self):
        return self.record_title

to_do/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from to_do.models import ToDoListTitle, Record


class UserAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']


class ToDiListCreateForm(ModelForm):
    class Meta:
        model = ToDoListTitle
        fields = ['title', 'user']


class RecordCreateForm(ModelForm):
    class Meta:
        model = Record
        fields = ['record_title', 'status', 'title']

to_do/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView

from to_do.forms import *
from to_do.models import ToDoListTitle, Record


class UserLoginView(LoginView):
    template_name = 'login.html'
    form_class = UserAuthenticationForm

    def get_success_url(self):
        return reverse('to-do-list')


class UserCreateView(SuccessMessageMixin, CreateView):
    template_name = 'registration.html'
    model = User
    form_class = UserRegistrationForm
    success_message = 'You have successfully registered!'

    def get_success_url(self):
        return reverse('login')


class ToDoListView(CreateView, ListView):
    model = ToDoListTitle
    template_name = 'to-do-list.html'
    paginate_by = 3
    form_class = ToDiListCreateForm
    context_object_name = 'to_do_list'
    success_url = reverse_lazy('to-do-list')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ToDoListView, self).get_context_data()
        context['records'] = Record.objects.all().select_related()
        return context


def to_do_list_delete(request, pk_to_do_list):
    to_do_list = ToDoListTitle.objects.get(pk=pk_to_do_list)
    to_do_list.delete()

    return redirect('to-do-list')


class RecordView(CreateView, ListView):
    model = Record
    template_name = 'to-do-list.html'
    form_class = RecordCreateForm
    success_url = reverse_lazy('to-do-list')


def record_delete(request, pk_record):
    record = Record.objects.get(pk=pk_record)
    record.delete()

    return redirect('to-do-list')


def record_update(request, pk_record):
    record = Record.objects.get(pk=pk_record)
    record.status = True
    record.save()

    return redirect("to-do-list")


def user_logout(request):
    logout(request)
    return redirect('login')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

to_do/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <section class="container">
        <div class="messages">
            {% if messages %}
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            {% endif %}
        </div>
        <div class="login">
            <h1>
                User authorization
            </h1>
            <form method="post" action="">
                {% csrf_token %}
                <div class="form-error">
                    {{ form.non_field_errors }}
                </div>
                <p>
                    <label for="id_username"></label>
                    <input type="text" name="username" value="" placeholder="Username" id="id_username">
                </p>
                <div class="form-error">
                    {{ form.username.errors }}
                </div>
                <p>
                    <label for="id_password"></label>
                    <input type="password" name="password" value="" placeholder="Password" id="id_password">
                </p>
                <div class="form-error">
                    {{ form.password.errors }}
                </div>
                <p class="remember_me">
                    <label>
                        <input type="checkbox" name="remember_me" id="remember_me">
                        Remember me on this computer
                    </label>
                </p>
                <p class="submit">
                    <a href="{% url 'to-do-list' %}">
                        <input type="submit" name="commit" value="Login">
                    </a>
                </p>
            </form>
            <div class="login-help">
                <a href="{% url 'registration' %}">
                    <p>
                        Need an account?
                    </p>
                </a>
            </div>
        </div>
    </section>
{% endblock %}

to_do/templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    {#    <link rel="stylesheet" href="{% static 'css/base.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}

{% block title %}
    Registration
{% endblock %}

{% block body %}
    <section class="container">
        <div class="login">
            <h1>
                User registration
            </h1>
            <form method="post" action="">
                {% csrf_token %}
                <div class="form-error">
                    {{ form.non_field_errors }}
                </div>
                <p>
                    <input type="text" name="username" placeholder="Username" id="id_username">
                    <label for="id_username" class="form-error">
                    </label>
                </p>
                <div class="form-error">
                    {{ form.username.errors }}
                </div>
                <p>
                    <input type="text" name="email" placeholder="Email" id="id_email">
                    <label for="id_email" class="form-error">
                    </label>
                </p>
                <div class="form-error">
                    {{ form.email.errors }}
                </div>
                <p>
                    <input type="text" name="first_name" placeholder="First_name" id="id_first_name">
                    <label for="id_first_name" class="form-error">
                    </label>
                </p>
                <div class="form-error">
                    {{ form.first_name.errors }}
                </div>
                <p>
                    <input type="text" name="last_name" placeholder="Last_name" id="id_last_name">
                    <label for="id_last_name" class="form-error">
                    </label>
                </p>
                <div class="form-error">
                    {{ form.last_name.errors }}
                </div>
                <p>
                    <input type="password" name="password1" placeholder="Password" id="id_password1">
                    <label for="id_password1" class="form-error">
                    </label>
                </p>
                <div class="form-error">
                    {{ form.password1.errors }}
                </div>
                <p>
                    <input type="password" name="password2" placeholder="Repeat the password" id="id_password2">
                    <label for="id_password2"></label>
                </p>
                <div class="form-error">
                    {{ form.password2.errors }}
                </div>
                <p class="submit">
                    <a href="{% url 'login' %}">
                        <input type="submit" name="commit" value="Registration">
                    </a>
                </p>
            </form>
        </div>
    </section>
{% endblock %}

to_do/templates/to-do-list.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    {#    <link rel="stylesheet" href="{% static 'css/to-do-list.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/to-do-list.css' %}">
{% endblock %}

{% block title %}
    My to do list
{% endblock %}

{% block body %}
    <a href="{% url 'logout' %}">
        <button class="Logout">
            Logout
        </button>
    </a>
    <div class="content">
        <h1>
            My to do list
        </h1>
        <form action="" method="post">
            {% csrf_token %}
            <div id="app-list" class="list">
                <label for="id_title"></label>
                <input class="input" type="text" name="title" maxlength="25" id="id_title"
                       placeholder="Введите название таска">
                <label for="id_user"></label>
                <select name="user" required="" id="id_user" hidden="hidden">
                    <option value="{{ request.user.pk }}" hidden="hidden">
                        {{ request.user }}
                    </option>
                </select>
                <button class="btn btn-add" type="submit">
                    Add task
                </button>
            </div>
        </form>
    </div>
    <div class="task-container">
        {% for i in to_do_list %}
            {% if i.user.pk == request.user.pk %}
                <div class="task">
                    <header>
                        <h2>
                            {{ i.title }}
                        </h2>
                        <a href="{% url 'to-do-list-delete' i.pk %}" class="basket">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                                 class="bi bi-trash3" viewBox="0 0 16 16">
                                <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5
    0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885
    16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1
    0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5
    5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.
    5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                            </svg>
                        </a>
                    </header>
                    <form method="post" action="{% url 'add-record' %}">
                        {% csrf_token %}
                        <label for="id_record_title"></label>
                        <input type="text" name="record_title" maxlength="45" required="" id="id_record_title"
                               class="todo-input" placeholder="Введите пункт"/>
                        <label for="id_status"></label>
                        <input type="checkbox" name="status" id="id_status" hidden="hidden">
                        <select name="title" required="" id="id_title" hidden="hidden">
                            <option value="{{ i.pk }}" hidden="hidden">
                                {{ i }}
                            </option>
                        </select>
                        <button type="submit" class="image">
                            &#10010;
                        </button>
                    </form>
                    <br>
                    <div class="records">
                        <div>Records:</div>
                    </div>
                    <div class="wrapper">
                        {% for record in records %}
                            {% if record.title == i %}
                                <div class="html-teg">
                                    &#9997;
                                </div>
                                {% if record.status == False %}
                                    <div class="left_block">
                                        {{ record.record_title }}
                                    </div>
                                {% else %}
                                    <div class="left_block-tr">
                                        {{ record.record_title }}
                                    </div>
                                {% endif %}
                                <div class="right_block">
                                    {% if record.status == False %}
                                        <a href="{% url 'record_update' record.pk %}">
                                            <input type="button" value="✔️" title="Add Task" class="input-update">
                                        </a>
                                    {% else %}
                                        <span class="tick">	&#10004;</span>
                                    {% endif %}
                                    <a href="{% url 'record-delete' record.pk %}">
                                        <input type="button" value="❌" title="Remove Task" class="input-delete">
                                    </a>
                                </div>
                                <br>
                                <br>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="pagination">
        {% if page_obj.has_other_pages %}
            {% if page_obj.has_previous %}
                <a class="link-pagination" href="?page={{ page_obj.paginator.num_page }}">First</a>
                <a class="link-pagination" href="?page={{ page_obj.previous_page_number }}">&laquo</a>
            {% endif %}
            {% for p in paginator.page_range %}
                {% if page_obj.number == p %}
                    <span class="page-link">{{ p }}</span>
                {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                    <a class="link-pagination" class="page-link" href="?page={{ p }}">{{ p }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="link-pagination" href="?page={{ page_obj.next_page_number }}">&raquo</a>
                <a class="link-pagination" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}